### PR TITLE
added my changes

### PR DESCRIPTION
**Pull request by parisapahlevan**
Please review

### CODE REVIEW

**Review by Camiloagudelo4368 — CHANGES_REQUESTED** [review]
Paris you should change the name of your files because it will create a conflict with what Anthony made in the index page, that page should be call "search.html" and the javascript file "search.js" into the assets/javascript.... in term to publish that and everyone can test it

**Review by Camiloagudelo4368 — CHANGES_REQUESTED** [review]
we have in the master branch the structure assets/javascript/… to store the javascript files, you forgot to put it in that directory

**Review by Camiloagudelo4368 — CHANGES_REQUESTED** [review]
We have in the master branch the structure assets/javascript/… to store the javascript files, you forgot to put it in that directory

**Comment by parisapahlevan** [comment]
Please review the new changes @Camiloagudelo4368, @Frenshy1031 and @odavom.
I tested the files and they all work. Please feel free to add or edit the CSS styles as you like.

**Review by odavom — APPROVED** [review]
I'll make a new css file called search.css

thanks Paris - I has some notes I sent out over slack

**Review by odavom — APPROVED** [review]

**Review by odavom — APPROVED** [review]

**Review by Camiloagudelo4368 — APPROVED** [review]
We have in the master branch the structure assets/javascript/… to store the javascript files, you forgot to put it in that directory

**Pull request merged**
